### ISSUE TITLE
Update FTP downloads to get file mod time

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_resources#25]
Try using this library: http://ftputil.sschwarzer.net/trac/wiki/Documentation#retrieving-information-about-directories-files-and-links

to get file mod time for FTP servers that don't support MLSD.

This is needed to determine if we need to download the source database files for re-processing.  Update bel_resources to use this in the utils section of bel_resources/tools/utils if it works.

**Comment by davidchen** [comment]
Updated under https://github.com/belbio/bel_resources/commit/493a149b518e37d711898125387ce186bb355b08.
