### ISSUE TITLE
Slow equivalence query

### ISSUE THREAD

**Issue by wshayes** [belbio/bel_resources#96]
FOR vertex, edge IN 1..10 ANY 'equivalence_nodes/RGD:Calm1' equivalence_edges RETURN DISTINCT {term_id: vertex._key, namespace: vertex.namespace}

https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=2257

https://www.uniprot.org/uniprot/P0DP29#cross_references

**Comment by ncatlett** [comment]
P62805 (HIST1H4A) is also slow

**Comment by wshayes** [comment]
Natalie found "RGD file and website both map RGD:Calm1 to SwissProt Calm1, Calm2, Calm3" - so the extra equivalences for Calm1 are correct - just need to figure out why it's so slow.
